<!DOCTYPE html>
<html lang="pt-br" xmlns="http://www.w3.org/1999/html">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="../../../public/assets/css/style.css">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/377f60039f.js"></script>
    <style>
        .sameWidth {
            width: 120%;
            align
        }

        .titleModal{
            margin-left: 0px;
        }

        .space{
            margin-left: 35%;
        }

        .emailRec{
            width: 200%;
        }

        .space1{
            margin-top: 50px;
        }

        .space2{
            margin-left: 29%;
        }

        .alerta{
            display: none;
            position: fixed;
            margin-top: 0px;
            margin-left: 70%;
            width: 25%;
        }
        form#form_login{
            margin-top: 5%;
        }

        legend{
            margin-left: 20px;
            margin-top: 10px;
        }

                .sameWidth {
            width: 120%;
        
        }

    </style>


    <legend>Cadastro de Cliente</legend>
    <hr>
                        <div  class="container">
                            <form  id="form_cliente" method="get" action="">

                                
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="nomeCliente">Nome Completo:</label>
                                        <input class="form-control space2" type="text" name="nomeCliente" id="nomeCliente" placeholder="Nome do Cliente" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="endCliente">Endereço:</label>
                                        <input class="form-control space2" type="text" name="endCliente" id="endCliente" placeholder="Endereço" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="empresaCliente">Empresa:</label>
                                        <input class="form-control space2" type="text" name="empresaCliente" id="empresaCliente" placeholder="Empresa" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="cpfCliente">CPF/CNPJ:</label>
                                        <input class="form-control space2" type="text" name="cpfCliente" id="cpfCliente" placeholder="" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="emailCliente">Email:</label>
                                        <input  class="form-control space2 " id="emailCliente" name="emailCliente" placeholder="exemplo@exemplo.com" type="email" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="telefoneCliente">Telefone:</label>
                                        <input class="form-control space2" type="number" name="telefoneCliente" id="telefoneCliente" placeholder="XX XXXXX-XXXXX" min="0" required>
                                    </div>
                                </div>
                                <hr>
                                <div class="row justify-content-center">
                                    <div class="row">
                <div class="col col-6 form-group">
                    <button id="clienteBack" name="clienteBack" type="button" class="sameWidth btn btn-outline-info" >Voltar</button>
                </div>

                <div class="col col-6 form-group">
                    <input id="cadastrarCliente" type="submit" value="Cadastrar" name="cadastrarCliente" class="sameWidth btn btn-success">
                </div>
            </div>
                                </div>
                                
                            </form>
                        </div>
                    

<footer>

</footer>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
</body>
</html>

<!-- importando ja

vascript do bootstrap -->