<?php
$erro = isset($_GET['erro']) ? $_GET['erro']: null;

?>

<!DOCTYPE html>
<html lang="pt-br" xmlns="http://www.w3.org/1999/html">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="../../../public/assets/css/style.css">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/377f60039f.js"></script>
    <style>
        .sameWidth {
            width: 120%;
            align
        }

        .titleModal{
            margin-left: 0px;
        }

        .space{
            margin-left: 35%;
        }

        .emailRec{
            width: 200%;
        }

        .space1{
            margin-top: 50px;
        }

        .space2{
            margin-left: 29%;
        }

        .alerta{
            display: none;
            position: fixed;
            margin-top: 0px;
            margin-left: 70%;
            width: 25%;
        }
        form#form_login{
            margin-top: 5%;
        }

    </style>
</head>
<body>
<div id="successRecovery" class="alert alert-success alert-dismissible nav-fixed-top alerta" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Solicitação realizada com sucesso!</strong> Verifique seu email após alguns instantes.
</div>

<div id="failRecovery" class="alert alert-danger alert-dismissible navbar-fixed-top alerta" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Ocorreu um erro!</strong> Tente novamente após alguns instantes.
</div>


<!-- ALERTS -->


<?php
if ($erro == 1){
    echo'<script type="text/javascript">
            $(document).ready(function(){
                 $("#failRecovery").fadeIn(1000);
                $("#failRecovery").fadeOut(5000);
            });
            </script>';
}else if ($erro == 0 and $erro != null){
    echo'<script type="text/javascript">
            $(document).ready(function(){
                 $("#successRecovery").fadeIn(400);
                $("#successRecovery").fadeOut(5000);
            });
            </script>';
}else if ($erro != null and $erro != ''){

}
?>



<!-- Fomulário de Login de usuario -->
<form id="form_login" method="post" action="/Gerencia-Obras/public/login">

    <div  class="container">
        <div  class="row justify-content-center">
            <div class="col col-6">
                <div class="form-group">
                    <label for="usuario_cpf">Login <i class="fa fa-sign-in" aria-hidden="true"></i></label>
                </div>
                <div class="form-group">
                    <label for="cpfUsuario">Email:</label>
                    <input  class="form-control" id="cpfUsuario" name="emailUsuario" placeholder="exemplo@exemplo.com" type="email" required>
                </div>
                <div class="form-group">
                    <label for="senhaUsuario">Senha:</label>
                    <input class="form-control" type="password" name="senhaUsuario" id="senhaUsuario" placeholder="Senha do usuario" required>
                </div>
            </div>
        </div>

        <p>
            <button data-toggle="modal" data-target="#myModal1" id="forgetPassword" name="forgetPassword" type="button" class="btn btn-link btn-sm btn-block" >Esqueci minha senha</button>
        </p>



        <div class="row justify-content-center container" >
            <div class="row">

                <div class="col col-6 form-group">
                    <button data-toggle="modal" data-target="#myModal2" id="cadastrarUsuario" name="cadastrarUsuario" type="button" class="sameWidth btn btn-outline-info" >Cadastrar-se</button>
                </div>

                <div class="col col-6 form-group">
                    <input id="entrar" type="submit" value="Entrar" name="submit" class="sameWidth btn btn-success">
                </div>

            </div>
        </div>



        <!-- <input href="" type="submit" class="btn btn-success" id="btn_login_usuario" value="Entrar" name="btn_login_usuario"> -->
    </div>
    </div>

    </div>
    </div>
</form>

<!-- Modal -->
<form method="post" action="#">
<div class="modal fade space1" id="myModal1" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title titleModal col-11">Recuperação de Senha</h4>
                <button type="button" class="close col-1" data-dismiss="modal">&times;</button>

            </div>
            <div class="modal-body">
                <div  >
                    <div  class="row">
                        <div class="col-sm-5 col-5 col-md-5 col-lg-5 col-xl-5">
                            <div class="form-group">
                                <label class="space" for="emeilRecovery">Email:</label>
                                <input  class="form-control space emailRec" id="emeilRecovery" name="emeilRecovery" placeholder="exemplo@exemplo.com" type="email" required>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" name="solicitaRecovery" id="solicitaRecovery" class="btn btn-success" data-dismiss="modal">Enviar Solicitação</button>
            </div>
        </div>

    </div>
</div>
</form>

<!-- / Fomulário de Login -->

    <!-- Fomulário de Cadastro de usuario -->
        <div class="modal fade space1" id="myModal2" role="dialog">
            <div class="modal-dialog">

                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title titleModal col-11">Cadastro de Usuário</h4>
                        <button type="button" class="close col-1" data-dismiss="modal">&times;</button>

                    </div>
                    <div class="modal-body">

                        <div  class="container">
                            <form  id="form_cadastro" method="get" action="/Gerencia-Obras/public/cadastro">

                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="emailCadastro">Email:</label>
                                        <input  class="form-control space2 emailCadastro" id="emeilCadastro" name="emeilRecovery" placeholder="exemplo@exemplo.com" type="email" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="nomeCadastro">Nome Completo:</label>
                                        <input class="form-control space2" type="text" name="nomeCadastro" id="nomeCadastro" placeholder="Nome do usuário" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="endCadastro">Endereço:</label>
                                        <input class="form-control space2" type="text" name="endCadastro" id="endCadastro" placeholder="Endereço" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="empresaCadastro">Empresa:</label>
                                        <input class="form-control space2" type="text" name="empresaCadastro" id="empresaCadastro" placeholder="Empresa" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="cpfCadastro">CPF:</label>
                                        <input class="form-control space2" type="text" name="cpfCadastro" id="cpfCadastro" placeholder="XXX.XXX.XXX-XX" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="senhaCadastro">Senha:</label>
                                        <input class="form-control space2" type="password" name="senhaCadastro" id="senhaCadastro" placeholder="Senha do usuário" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <label class="space2" for="nivelAcesso">Nivel de Acesso:</label>
                                        <input class="form-control space2" type="number" name="nivelAcesso" id="nivelAcesso" placeholder="Nivel de acesso" min="0" required>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8 col-8 col-md-8">
                                        <div class="modal-footer">
                                            <input type="submit" name="solicitaCadastro" id="solicitaCadastro" class="btn btn-success" value="Cadastrar-se">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">

                                </div>
                            </form>
                        </div>
                    </div>
            </div>
            
        </div>
    </div>

<footer>

</footer>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
</body>
</html>

<!-- importando ja

vascript do bootstrap -->