
<hr>
<form  id="form_cliente" method="post" action="/Gerencia-Obras/public/home/cadastro/cliente/form">
<div  class="container">
        <div class="row">
            <div class="col-sm-8 col-8 col-md-8">
                <div class="form-group ">
                    <label class="space2" for="nomeCliente">Nome Completo:</label>
                    <input class="form-control space2" type="text" name="nomeCliente" id="nomeCliente" placeholder="Nome do Cliente" required>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-8 col-8 col-md-8">
                <div class="form-group">
                    <label class="space2" for="endCliente">Endereço:</label>
                    <input class="form-control space2" type="text" name="endCliente" id="endCliente" placeholder="Endereço" required>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 col-8 col-md-8">
                <div class="form-group">
                    <label class="space2" for="empresaCliente">Empresa:</label>
                    <input class="form-control space2" type="text" name="empresaCliente" id="empresaCliente" placeholder="Empresa" required>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 col-8 col-md-8">
                <div class="form-group">
                    <label class="space2" for="cpfCliente">CPF/CNPJ:</label>
                    <input class="form-control space2" type="text" name="cpfCliente" id="cpfCliente" placeholder="" required>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 col-8 col-md-8">
                <div class="form-group">
                    <label class="space2" for="emailCliente">Email:</label>
                    <input  class="form-control space2 " id="emailCliente" name="emailCliente" placeholder="exemplo@exemplo.com" type="email" required>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 col-8 col-md-8">
                <div class="form-group">
                    <label class="space2" for="telefoneCliente">Telefone:</label>
                    <input class="form-control space2" type="number" name="telefoneCliente" id="telefoneCliente" placeholder="XX XXXXX-XXXXX" min="0" required>
                </div>
            </div>
        </div>
        <hr>
        <div class="row justify-content-center">
            <div class="row">
                <div class="col col-6">
                    <div class="col col-6 form-group">
                        <button id="clienteBack" name="clienteBack" type="button" class="sameWidth btn btn-outline-info" >Voltar</button>
                    </div>
                </div>
                <div class="col col-6">
                    <div class="col col-6 form-group">
                        <input id="cadastrarCliente" type="submit" value="Cadastrar" name="cadastrarCliente" class="sameWidth btn btn-success">
                    </div>
                </div>
            </div>
        </div>
</div>
</form>