<style>
    .sameWidth {
        width: 120%;
        align
    }

    .titleModal{
        margin-left: 0px;
    }

    .space{
        margin-left: 35%;
    }

    .emailRec{
        width: 200%;
    }

    .space1{
        margin-top: 50px;
    }

    .space2{
        margin-left: 29%;
    }

    .alerta{
        display: none;
        position: fixed;
        margin-top: 0px;
        margin-left: 70%;
        width: 25%;
    }
    form#form_login{
        margin-top: 5%;
    }

    legend{
        margin-left: 20px;
        margin-top: 10px;
    }

    .sameWidth {
        width: 120%;

    }

</style>

<br>
<br>
<hr>
<div  class="container">
    <form  id="form_cliente" method="post" action="/Gerencia-Obras/public/home/cadastro/cliente/form">


        <div class="row">
            <div class="form-group col-sm-8 col-8 col-md-8">
                <label class="space2" for="nomeCliente">Nome Completo:</label>
                <input class="form-control space2" type="text" name="nomeCliente" id="nomeCliente" placeholder="Nome do Cliente" required>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-sm-8 col-8 col-md-8">
                <label class="space2" for="endCliente">Endereço:</label>
                <input class="form-control space2" type="text" name="endCliente" id="endCliente" placeholder="Endereço" required>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-8 col-8 col-md-8">
                <label class="space2" for="empresaCliente">Empresa:</label>
                <input class="form-control space2" type="text" name="empresaCliente" id="empresaCliente" placeholder="Empresa" required>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-8 col-8 col-md-8">
                <label class="space2" for="cpfCliente">CPF/CNPJ:</label>
                <input class="form-control space2" type="text" name="cpfCliente" id="cpfCliente" placeholder="" required>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-8 col-8 col-md-8">
                <label class="space2" for="emailCliente">Email:</label>
                <input  class="form-control space2 " id="emailCliente" name="emailCliente" placeholder="exemplo@exemplo.com" type="email" required>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-8 col-8 col-md-8">
                <label class="space2" for="telefoneCliente">Telefone:</label>
                <input class="form-control space2" type="number" name="telefoneCliente" id="telefoneCliente" placeholder="XX XXXXX-XXXXX" min="0" required>
            </div>
        </div>
        <hr>
        <div class="row justify-content-center">
            <div class="row">
                <div class="col col-6 form-group">
                    <button id="clienteBack" name="clienteBack" type="button" class="sameWidth btn btn-outline-info" >Voltar</button>
                </div>

                <div class="col col-6 form-group">
                    <input id="cadastrarCliente" type="submit" value="Cadastrar" name="cadastrarCliente" class="sameWidth btn btn-success">
                </div>
            </div>
        </div>

    </form>
</div>

