<?php
session_start();
if (!isset($_SESSION['nivelAcessoUsuario'])){
    header('Location:/Gerencia-Obras/public?erro=1');
}
$erro = isset($_GET['erro']) ? $_GET['erro']: null;

?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Gerencia Obras</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/377f60039f.js"></script>


    <!--<link rel="stylesheet" type="text/css" href="/public/App/assets/css/menu.css">-->
    <style><?php include_once "../App/assets/css/menu.css"; ?></style>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light barraNav" style="background-color: #e1f5fe;">
        
        <div >
            <img src="../assets/logo.png" class="img-fluid m-x-auto logo" alt="Responsive image">
        </div>        
    
</nav>


<div class="wrapper container">
  <div class="row">
    <div class="col col-3">

    <input type="checkbox" id="navigation"/>
    <label for="navigation">
        <i class="fa fa-bars plus" aria-hidden="true"></i>
    </label>

    <nav id="menu" class="menuLateral mySidenav nav_sideMenu" data-children=".subMenu">
        <ul class="ulSide">

            <li class="logOut text-center">
                <a data-toggle="collapse" href="#collapseLog" aria-expanded="false" aria-controls="collapseLog" data-parent="logOut" class="logOut1 menuLateralA">
                    <i class="fa fa-user-circle" aria-hidden="true" style="padding-right: 5px;"></i>
                    <span class="logout"></span>
                    <span class="text-center" style="font-size: 18px;"> Usuário <?php echo$_SESSION['nomeUsuario'] ?> </span>

                    <i class="text-right fa fa-angle-down" aria-hidden="true" style="padding-left: 23%;"></i>
                    <br>
                    <p class="text-center small" style="font-size: 12px;">Seja bem vindo!</p>
                </a>
                <hr>
                <ul class="collapse" id="collapseLog" role="tabpanel">
                    <li>
                        <div class="navbar-login">
                            <div class="row">
                                
                                <div class="col-lg-8 ">
                                    <p class="text-center small"><?php echo $_SESSION['emailUsuario'] ?></p>
                                   
                                   <a href="/Gerencia-Obras/public/logout" id="logout" name="logout" class="btn btn-danger btn-block sairLog">Sair <i class="fa  fa-sign-out" aria-hidden="true"></i></a>
                                   <hr>
                                </div>
                            </div>
                        </div>
                    </li>
                                        
                </ul>
            </li>

            <li class="Menu">
                <a data-toggle="collapse" href="#collapseCadastro" aria-expanded="false" aria-controls="collapseCadastro" data-parent="menu" class="Menu menuLateralA">
                    <i class="fa fa-server iconNav" aria-hidden="true" >
                        Cadastro
                    </i>
                    <i class="fa fa-angle-down iconDown" aria-hidden="true"></i>
                </a>
                  <ul class=" collapse" id="collapseCadastro" role="tabpanel">
                    <li class=""><a href="/Gerencia-Obras/public/home/cadastro/cliente" class="menuLateralA subMenu">Clientes</a></li>
                    <hr>
                  </ul>
            </li>
            <li>
                <a href="" class="menuLateralA"><i class="fa fa-wrench iconNav" aria-hidden="true">Obras</i></a>
            </li>
            
            <hr>
            
        </ul>
    </nav>

    </div>
      <div id="successRecovery" class="alert alert-success alert-dismissible nav-fixed-top alerta" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong>Solicitação realizada com sucesso!</strong> Verifique seu email após alguns instantes.
      </div>

      <div id="failRecovery" class="alert alert-danger alert-dismissible navbar-fixed-top alerta" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong>Ocorreu um erro!</strong> Tente novamente após alguns instantes.
      </div>


      <?php
      if ($erro == 1){
          echo'<script type="text/javascript">
            $(document).ready(function(){
                 $("#failRecovery").fadeIn(1000);
                $("#failRecovery").fadeOut(5000);
            });
            </script>';
      }else if ($erro == 0 and $erro != null){
          echo'<script type="text/javascript">
            $(document).ready(function(){
                 $("#successRecovery").fadeIn(400);
                $("#successRecovery").fadeOut(5000);
            });
            </script>';
      }
      ?>


<div class="conteudo col col-9">

    <?php $this->content() ?>
</div>

    </div>
</div>




<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>