<?php
session_start();
if (!isset($_SESSION['nivelAcessoUsuario'])){
    header('Location:/Gerencia-Obras/public?erro=1');
}
?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Gerencia Obras</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/377f60039f.js"></script>

        <link rel="stylesheet" type="text/css" href="../assets/css/menu.css">

</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light barraNav" style="background-color: #e1f5fe;">
        
        <div >
            <img src="../assets/logo.png" class="img-fluid m-x-auto logo" alt="Responsive image">
        </div>        
    
</nav>


<div class="wrapper container">
  <div class="row">
    <div class="col col-3">

    <input type="checkbox" id="navigation"/>
    <label for="navigation">
        <i class="fa fa-bars plus" aria-hidden="true"></i>
    </label>

    <nav id="menu" class="menuLateral mySidenav nav_sideMenu" data-children=".subMenu">
        <ul class="ulSide">

            <li class="logOut text-center">
                <a data-toggle="collapse" href="#collapseLog" aria-expanded="false" aria-controls="collapseLog" data-parent="logOut" class="logOut1 menuLateralA">
                    <i class="fa fa-user-circle" aria-hidden="true" style="padding-right: 5px;"></i>
                    <span class="logout"></span>
                    <span class="text-center" style="font-size: 18px;"> Usuário <?php echo$_SESSION['nomeUsuario'] ?> </span>

                    <i class="text-right fa fa-angle-down" aria-hidden="true" style="padding-left: 23%;"></i>
                    <br>
                    <p class="text-center small" style="font-size: 12px;">Seja bem vindo!</p>
                </a>
                <hr>
                <ul class="collapse" id="collapseLog" role="tabpanel">
                    <li>
                        <div class="navbar-login">
                            <div class="row">
                                
                                <div class="col-lg-8 ">
                                    <p class="text-center small">email@email<?php echo $_SESSION['emailUsuario'] ?></p>
                                   
                                   <a href="logout" id="logout" name="logout" class="btn btn-danger btn-block sairLog">Sair <i class="fa  fa-sign-out" aria-hidden="true"></i></a>
                                   <hr>
                                </div>
                            </div>
                        </div>
                    </li>
                                        
                </ul>
            </li>

            <li class="Menu">
                <a data-toggle="collapse" href="#collapseCadastro" aria-expanded="false" aria-controls="collapseCadastro" data-parent="menu" class="Menu menuLateralA">
                    <i class="fa fa-server iconNav" aria-hidden="true" >
                        Cadastro
                    </i>
                    <i class="fa fa-angle-down iconDown" aria-hidden="true"></i>
                </a>
                  <ul class=" collapse" id="collapseCadastro" role="tabpanel">
                    <li class=""><a href="" class="menuLateralA subMenu">Clientes</a></li>
                    <hr>
                  </ul>
            </li>
            <li>
                <a href="" class="menuLateralA"><i class="fa fa-wrench iconNav" aria-hidden="true">Obras</i></a>
            </li>
            
            <hr>
            
        </ul>
    </nav>

    </div>

<div class="conteudo col col-9">
       
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at augue nec nunc fermentum imperdiet in in mauris. Suspendisse sollicitudin arcu velit, vitae mattis ex convallis id. Cras tristique id elit eu sollicitudin. Quisque volutpat pulvinar tincidunt. Nam id tempor mauris, quis facilisis magna. Sed vestibulum libero rhoncus nisl sagittis, id facilisis augue ultrices. Duis molestie odio ac felis eleifend, ut sodales eros posuere. Mauris viverra sem vel turpis fermentum, at pretium odio maximus. Nulla at dui sit amet lorem laoreet dignissim a id velit. Nam vel ex vehicula, finibus nisl a, sagittis dui. Pellentesque porta volutpat erat eget feugiat. Pellentesque ut finibus nibh. Nunc ut lorem in lorem varius lobortis. Integer sit amet velit vestibulum, ullamcorper risus non, feugiat massa.

Phasellus ut justo et ante feugiat placerat. Etiam eu dui nec est dictum commodo. Nam nec suscipit diam. Cras posuere placerat urna sed tincidunt. Aliquam mollis mi sed augue tincidunt auctor. Integer consequat placerat nisi sed cursus. Sed urna diam, feugiat in auctor ac, vestibulum ac nibh. Cras ligula justo, sodales eget elementum eget, gravida et sapien. Praesent eget tristique justo. Nullam vel magna accumsan, malesuada justo sit amet, posuere nulla. Aliquam at hendrerit metus. Maecenas feugiat sollicitudin consequat. Nullam eleifend sed neque nec dictum.

Duis sed odio commodo, sagittis tortor eget, eleifend sem. Fusce nulla dui, fringilla a facilisis sit amet, placerat vel metus. Nulla sodales tincidunt egestas. Sed pulvinar, turpis quis tincidunt eleifend, erat elit luctus nibh, in imperdiet mauris dui a lorem. In tincidunt mollis risus sed pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean mattis tortor est, sed eleifend mauris sollicitudin vel. Maecenas dapibus enim augue, vel bibendum mi rutrum at. Phasellus at viverra erat, et volutpat dui. Ut sed nibh efficitur justo tempor viverra. Nunc felis tortor, auctor a commodo at, tristique viverra dui. Suspendisse vulputate non quam non rutrum. Mauris gravida turpis eget ante tempus, nec hendrerit dui placerat. Nullam felis felis, feugiat nec mi id, convallis tristique justo. Sed accumsan, orci at vestibulum cursus, ligula urna varius sapien, id sollicitudin justo nisl et ex.

Morbi sit amet lacus nec purus consectetur pharetra. In et tempor eros, quis mollis mauris. Phasellus faucibus, dui quis eleifend feugiat, leo odio imperdiet ante, ut mollis justo lacus non erat. Quisque ornare euismod turpis, eget consectetur leo. Suspendisse velit libero, egestas ac augue non, ultrices dignissim ante. Curabitur interdum nisl rhoncus condimentum elementum. Fusce tincidunt lectus vel enim ullamcorper, vel tincidunt urna mollis.

Duis nec leo feugiat, condimentum est sit amet, mollis tortor. Sed porttitor mauris leo, sed cursus justo sollicitudin ac. Vivamus ultricies justo tortor, nec imperdiet quam tristique id. Curabitur semper aliquam pretium. Nulla vitae lorem ipsum. Pellentesque a massa nec turpis tempus vulputate in id quam. Aliquam consequat dolor ut augue vehicula, convallis mattis risus euismod. Etiam in leo rhoncus, semper urna vestibulum, ultricies nulla.

        </div>

    </div>
</div>




<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>